//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class B2bUserGroupCompanyMappings : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fB2bUserId;
        [Indexed(Name = @"IX_B2bUserGroupCompanyMappings_B2bUserId", Unique = true)]
        [Size(450)]
        public string B2bUserId
        {
            get { return fB2bUserId; }
            set { SetPropertyValue<string>(nameof(B2bUserId), ref fB2bUserId, value); }
        }
        string fB2bUserGroupCompanyName;
        [Size(SizeAttribute.Unlimited)]
        public string B2bUserGroupCompanyName
        {
            get { return fB2bUserGroupCompanyName; }
            set { SetPropertyValue<string>(nameof(B2bUserGroupCompanyName), ref fB2bUserGroupCompanyName, value); }
        }
        string fUserName;
        [Size(SizeAttribute.Unlimited)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
    }

}
