//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class CompaniesCOneMastersV1Indexes : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        Guid fCompanyId;
        [Indexed(Name = @"IX_CompaniesCOneMastersV1Indexes_CompanyId")]
        public Guid CompanyId
        {
            get { return fCompanyId; }
            set { SetPropertyValue<Guid>(nameof(CompanyId), ref fCompanyId, value); }
        }
        long fCOneMasterV1Id;
        public long COneMasterV1Id
        {
            get { return fCOneMasterV1Id; }
            set { SetPropertyValue<long>(nameof(COneMasterV1Id), ref fCOneMasterV1Id, value); }
        }
        DateTime fCreatedAt;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<DateTime>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
    }

}
