//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class CompanyPermissions : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Companies fCompanyId;
        [Association(@"CompanyPermissionsReferencesCompanies")]
        public Companies CompanyId
        {
            get { return fCompanyId; }
            set { SetPropertyValue<Companies>(nameof(CompanyId), ref fCompanyId, value); }
        }
        string fShipperCode;
        [Size(SizeAttribute.Unlimited)]
        public string ShipperCode
        {
            get { return fShipperCode; }
            set { SetPropertyValue<string>(nameof(ShipperCode), ref fShipperCode, value); }
        }
        string fPattern;
        [Size(SizeAttribute.Unlimited)]
        public string Pattern
        {
            get { return fPattern; }
            set { SetPropertyValue<string>(nameof(Pattern), ref fPattern, value); }
        }
        string fDeliveryCode;
        [Size(SizeAttribute.Unlimited)]
        public string DeliveryCode
        {
            get { return fDeliveryCode; }
            set { SetPropertyValue<string>(nameof(DeliveryCode), ref fDeliveryCode, value); }
        }
        string fSalesOfficeCode;
        [Size(SizeAttribute.Unlimited)]
        public string SalesOfficeCode
        {
            get { return fSalesOfficeCode; }
            set { SetPropertyValue<string>(nameof(SalesOfficeCode), ref fSalesOfficeCode, value); }
        }
        string fTransporterCode;
        [Size(SizeAttribute.Unlimited)]
        public string TransporterCode
        {
            get { return fTransporterCode; }
            set { SetPropertyValue<string>(nameof(TransporterCode), ref fTransporterCode, value); }
        }
        string fWarehouseCode;
        [Size(SizeAttribute.Unlimited)]
        public string WarehouseCode
        {
            get { return fWarehouseCode; }
            set { SetPropertyValue<string>(nameof(WarehouseCode), ref fWarehouseCode, value); }
        }
    }

}
