//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class ExcelExportInfos : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>(nameof(Id), ref fId, value); }
        }
        DateTime fRequestedOn;
        public DateTime RequestedOn
        {
            get { return fRequestedOn; }
            set { SetPropertyValue<DateTime>(nameof(RequestedOn), ref fRequestedOn, value); }
        }
        string fRequestedBy;
        [Size(SizeAttribute.Unlimited)]
        public string RequestedBy
        {
            get { return fRequestedBy; }
            set { SetPropertyValue<string>(nameof(RequestedBy), ref fRequestedBy, value); }
        }
        string fTargetedPage;
        [Size(SizeAttribute.Unlimited)]
        public string TargetedPage
        {
            get { return fTargetedPage; }
            set { SetPropertyValue<string>(nameof(TargetedPage), ref fTargetedPage, value); }
        }
        string fBlobName;
        [Size(SizeAttribute.Unlimited)]
        public string BlobName
        {
            get { return fBlobName; }
            set { SetPropertyValue<string>(nameof(BlobName), ref fBlobName, value); }
        }
        string fFunctionInstanceId;
        [Size(SizeAttribute.Unlimited)]
        public string FunctionInstanceId
        {
            get { return fFunctionInstanceId; }
            set { SetPropertyValue<string>(nameof(FunctionInstanceId), ref fFunctionInstanceId, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
    }

}
