//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    [Indices(@"BASE_CD", "DELIDATE_TX", "DELIVERYDESTINATION_CD", "ORDERDETNO_CD", "OWNER_CD", "SHIPEND_TX", "SLIPNO_TX", "TRANSPORTER1_CD", "WH_CD")]
    public partial class Idsoko_PicksV1 : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fBASE_CD;
        [Indexed(@"OWNER_CD;TRANSPORTER1_CD;DELIVERYDESTINATION_CD;SLIPNO_TX;DELIDATE_TX;ORDERDETNO_CD;WH_CD;SHIPEND_TX", Name = @"IX_Idsoko_PicksV1_BASE_CD_OWNER_CD_TRANSPORTER1_CD_DELIVERYDESTINATION_CD_SLIPNO_TX_DELIDATE_TX_ORDERDETNO_CD_WH_CD_SHIPEND_TX", Unique = true)]
        [Size(450)]
        public string BASE_CD
        {
            get { return fBASE_CD; }
            set { SetPropertyValue<string>(nameof(BASE_CD), ref fBASE_CD, value); }
        }
        string fBASE_TX;
        [Size(SizeAttribute.Unlimited)]
        public string BASE_TX
        {
            get { return fBASE_TX; }
            set { SetPropertyValue<string>(nameof(BASE_TX), ref fBASE_TX, value); }
        }
        int fSHIPH_ID;
        public int SHIPH_ID
        {
            get { return fSHIPH_ID; }
            set { SetPropertyValue<int>(nameof(SHIPH_ID), ref fSHIPH_ID, value); }
        }
        string fTYPESHIP_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPESHIP_CD
        {
            get { return fTYPESHIP_CD; }
            set { SetPropertyValue<string>(nameof(TYPESHIP_CD), ref fTYPESHIP_CD, value); }
        }
        string fTYPESHIP_TX;
        [Size(SizeAttribute.Unlimited)]
        public string TYPESHIP_TX
        {
            get { return fTYPESHIP_TX; }
            set { SetPropertyValue<string>(nameof(TYPESHIP_TX), ref fTYPESHIP_TX, value); }
        }
        string fSTART_DT;
        [Size(SizeAttribute.Unlimited)]
        public string START_DT
        {
            get { return fSTART_DT; }
            set { SetPropertyValue<string>(nameof(START_DT), ref fSTART_DT, value); }
        }
        string fEND_DT;
        [Size(SizeAttribute.Unlimited)]
        public string END_DT
        {
            get { return fEND_DT; }
            set { SetPropertyValue<string>(nameof(END_DT), ref fEND_DT, value); }
        }
        int fSTSHIP_ID;
        public int STSHIP_ID
        {
            get { return fSTSHIP_ID; }
            set { SetPropertyValue<int>(nameof(STSHIP_ID), ref fSTSHIP_ID, value); }
        }
        string fORDERNO_CD;
        [Size(SizeAttribute.Unlimited)]
        public string ORDERNO_CD
        {
            get { return fORDERNO_CD; }
            set { SetPropertyValue<string>(nameof(ORDERNO_CD), ref fORDERNO_CD, value); }
        }
        string fORDERNOSUB_CD;
        [Size(SizeAttribute.Unlimited)]
        public string ORDERNOSUB_CD
        {
            get { return fORDERNOSUB_CD; }
            set { SetPropertyValue<string>(nameof(ORDERNOSUB_CD), ref fORDERNOSUB_CD, value); }
        }
        string fCUSTOMERORDERNO_CD;
        [Size(SizeAttribute.Unlimited)]
        public string CUSTOMERORDERNO_CD
        {
            get { return fCUSTOMERORDERNO_CD; }
            set { SetPropertyValue<string>(nameof(CUSTOMERORDERNO_CD), ref fCUSTOMERORDERNO_CD, value); }
        }
        string fCUSTOMER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string CUSTOMER_CD
        {
            get { return fCUSTOMER_CD; }
            set { SetPropertyValue<string>(nameof(CUSTOMER_CD), ref fCUSTOMER_CD, value); }
        }
        string fORDERTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string ORDERTYPE_CD
        {
            get { return fORDERTYPE_CD; }
            set { SetPropertyValue<string>(nameof(ORDERTYPE_CD), ref fORDERTYPE_CD, value); }
        }
        string fENTRYTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string ENTRYTYPE_CD
        {
            get { return fENTRYTYPE_CD; }
            set { SetPropertyValue<string>(nameof(ENTRYTYPE_CD), ref fENTRYTYPE_CD, value); }
        }
        string fORDERDATE_DT;
        [Size(SizeAttribute.Unlimited)]
        public string ORDERDATE_DT
        {
            get { return fORDERDATE_DT; }
            set { SetPropertyValue<string>(nameof(ORDERDATE_DT), ref fORDERDATE_DT, value); }
        }
        string fSALESSHOP_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SALESSHOP_CD
        {
            get { return fSALESSHOP_CD; }
            set { SetPropertyValue<string>(nameof(SALESSHOP_CD), ref fSALESSHOP_CD, value); }
        }
        string fOWNER_CD;
        [Size(450)]
        public string OWNER_CD
        {
            get { return fOWNER_CD; }
            set { SetPropertyValue<string>(nameof(OWNER_CD), ref fOWNER_CD, value); }
        }
        string fOWNER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string OWNER_TX
        {
            get { return fOWNER_TX; }
            set { SetPropertyValue<string>(nameof(OWNER_TX), ref fOWNER_TX, value); }
        }
        string fCHANNELTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string CHANNELTYPE_CD
        {
            get { return fCHANNELTYPE_CD; }
            set { SetPropertyValue<string>(nameof(CHANNELTYPE_CD), ref fCHANNELTYPE_CD, value); }
        }
        string fTRANSPORTER1_CD;
        [Size(450)]
        public string TRANSPORTER1_CD
        {
            get { return fTRANSPORTER1_CD; }
            set { SetPropertyValue<string>(nameof(TRANSPORTER1_CD), ref fTRANSPORTER1_CD, value); }
        }
        string fTRANSPORTER2_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TRANSPORTER2_CD
        {
            get { return fTRANSPORTER2_CD; }
            set { SetPropertyValue<string>(nameof(TRANSPORTER2_CD), ref fTRANSPORTER2_CD, value); }
        }
        string fDELIVERYDESTINATION_CD;
        [Size(450)]
        public string DELIVERYDESTINATION_CD
        {
            get { return fDELIVERYDESTINATION_CD; }
            set { SetPropertyValue<string>(nameof(DELIVERYDESTINATION_CD), ref fDELIVERYDESTINATION_CD, value); }
        }
        string fDTNAME_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DTNAME_TX
        {
            get { return fDTNAME_TX; }
            set { SetPropertyValue<string>(nameof(DTNAME_TX), ref fDTNAME_TX, value); }
        }
        string fDTPOSTAL_CD;
        [Size(SizeAttribute.Unlimited)]
        public string DTPOSTAL_CD
        {
            get { return fDTPOSTAL_CD; }
            set { SetPropertyValue<string>(nameof(DTPOSTAL_CD), ref fDTPOSTAL_CD, value); }
        }
        string fDTADDRESS1_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DTADDRESS1_TX
        {
            get { return fDTADDRESS1_TX; }
            set { SetPropertyValue<string>(nameof(DTADDRESS1_TX), ref fDTADDRESS1_TX, value); }
        }
        string fDTADDRESS2_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DTADDRESS2_TX
        {
            get { return fDTADDRESS2_TX; }
            set { SetPropertyValue<string>(nameof(DTADDRESS2_TX), ref fDTADDRESS2_TX, value); }
        }
        string fDTADDRESS3_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DTADDRESS3_TX
        {
            get { return fDTADDRESS3_TX; }
            set { SetPropertyValue<string>(nameof(DTADDRESS3_TX), ref fDTADDRESS3_TX, value); }
        }
        string fDTADDRESS4_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DTADDRESS4_TX
        {
            get { return fDTADDRESS4_TX; }
            set { SetPropertyValue<string>(nameof(DTADDRESS4_TX), ref fDTADDRESS4_TX, value); }
        }
        string fDTTEL_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DTTEL_TX
        {
            get { return fDTTEL_TX; }
            set { SetPropertyValue<string>(nameof(DTTEL_TX), ref fDTTEL_TX, value); }
        }
        string fDIRECTDELIVERY_CD;
        [Size(SizeAttribute.Unlimited)]
        public string DIRECTDELIVERY_CD
        {
            get { return fDIRECTDELIVERY_CD; }
            set { SetPropertyValue<string>(nameof(DIRECTDELIVERY_CD), ref fDIRECTDELIVERY_CD, value); }
        }
        string fTYPEPLALLET_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPEPLALLET_CD
        {
            get { return fTYPEPLALLET_CD; }
            set { SetPropertyValue<string>(nameof(TYPEPLALLET_CD), ref fTYPEPLALLET_CD, value); }
        }
        string fSHIPBERTH_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SHIPBERTH_CD
        {
            get { return fSHIPBERTH_CD; }
            set { SetPropertyValue<string>(nameof(SHIPBERTH_CD), ref fSHIPBERTH_CD, value); }
        }
        string fSHIPPLAN_DT;
        [Size(SizeAttribute.Unlimited)]
        public string SHIPPLAN_DT
        {
            get { return fSHIPPLAN_DT; }
            set { SetPropertyValue<string>(nameof(SHIPPLAN_DT), ref fSHIPPLAN_DT, value); }
        }
        string fSLIPNO_TX;
        [Size(450)]
        public string SLIPNO_TX
        {
            get { return fSLIPNO_TX; }
            set { SetPropertyValue<string>(nameof(SLIPNO_TX), ref fSLIPNO_TX, value); }
        }
        string fCARRIER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string CARRIER_CD
        {
            get { return fCARRIER_CD; }
            set { SetPropertyValue<string>(nameof(CARRIER_CD), ref fCARRIER_CD, value); }
        }
        string fDELITYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string DELITYPE_CD
        {
            get { return fDELITYPE_CD; }
            set { SetPropertyValue<string>(nameof(DELITYPE_CD), ref fDELITYPE_CD, value); }
        }
        DateTime fDELIDATE_TX;
        public DateTime DELIDATE_TX
        {
            get { return fDELIDATE_TX; }
            set { SetPropertyValue<DateTime>(nameof(DELIDATE_TX), ref fDELIDATE_TX, value); }
        }
        string fDELITIME_CD;
        [Size(SizeAttribute.Unlimited)]
        public string DELITIME_CD
        {
            get { return fDELITIME_CD; }
            set { SetPropertyValue<string>(nameof(DELITIME_CD), ref fDELITIME_CD, value); }
        }
        string fCHARGETYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string CHARGETYPE_CD
        {
            get { return fCHARGETYPE_CD; }
            set { SetPropertyValue<string>(nameof(CHARGETYPE_CD), ref fCHARGETYPE_CD, value); }
        }
        string fGIFTTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string GIFTTYPE_CD
        {
            get { return fGIFTTYPE_CD; }
            set { SetPropertyValue<string>(nameof(GIFTTYPE_CD), ref fGIFTTYPE_CD, value); }
        }
        string fTYPETEMPERATURE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPETEMPERATURE_CD
        {
            get { return fTYPETEMPERATURE_CD; }
            set { SetPropertyValue<string>(nameof(TYPETEMPERATURE_CD), ref fTYPETEMPERATURE_CD, value); }
        }
        long fTOTALITEMPRICE_NR;
        public long TOTALITEMPRICE_NR
        {
            get { return fTOTALITEMPRICE_NR; }
            set { SetPropertyValue<long>(nameof(TOTALITEMPRICE_NR), ref fTOTALITEMPRICE_NR, value); }
        }
        long fTOTALPRICE_NR;
        public long TOTALPRICE_NR
        {
            get { return fTOTALPRICE_NR; }
            set { SetPropertyValue<long>(nameof(TOTALPRICE_NR), ref fTOTALPRICE_NR, value); }
        }
        long fTOTALTAX_NR;
        public long TOTALTAX_NR
        {
            get { return fTOTALTAX_NR; }
            set { SetPropertyValue<long>(nameof(TOTALTAX_NR), ref fTOTALTAX_NR, value); }
        }
        long fDELICHARGE_NR;
        public long DELICHARGE_NR
        {
            get { return fDELICHARGE_NR; }
            set { SetPropertyValue<long>(nameof(DELICHARGE_NR), ref fDELICHARGE_NR, value); }
        }
        long fGIFTCHARGE_NR;
        public long GIFTCHARGE_NR
        {
            get { return fGIFTCHARGE_NR; }
            set { SetPropertyValue<long>(nameof(GIFTCHARGE_NR), ref fGIFTCHARGE_NR, value); }
        }
        long fCODCHARGE_NR;
        public long CODCHARGE_NR
        {
            get { return fCODCHARGE_NR; }
            set { SetPropertyValue<long>(nameof(CODCHARGE_NR), ref fCODCHARGE_NR, value); }
        }
        long fDISCOUNT_NR;
        public long DISCOUNT_NR
        {
            get { return fDISCOUNT_NR; }
            set { SetPropertyValue<long>(nameof(DISCOUNT_NR), ref fDISCOUNT_NR, value); }
        }
        long fSALEDISCOUNT_NR;
        public long SALEDISCOUNT_NR
        {
            get { return fSALEDISCOUNT_NR; }
            set { SetPropertyValue<long>(nameof(SALEDISCOUNT_NR), ref fSALEDISCOUNT_NR, value); }
        }
        string fCOUPON_CD;
        [Size(SizeAttribute.Unlimited)]
        public string COUPON_CD
        {
            get { return fCOUPON_CD; }
            set { SetPropertyValue<string>(nameof(COUPON_CD), ref fCOUPON_CD, value); }
        }
        long fCOUPONDISCOUNT_NR;
        public long COUPONDISCOUNT_NR
        {
            get { return fCOUPONDISCOUNT_NR; }
            set { SetPropertyValue<long>(nameof(COUPONDISCOUNT_NR), ref fCOUPONDISCOUNT_NR, value); }
        }
        long fUSEPOINT_NR;
        public long USEPOINT_NR
        {
            get { return fUSEPOINT_NR; }
            set { SetPropertyValue<long>(nameof(USEPOINT_NR), ref fUSEPOINT_NR, value); }
        }
        long fADDPOINT_NR;
        public long ADDPOINT_NR
        {
            get { return fADDPOINT_NR; }
            set { SetPropertyValue<long>(nameof(ADDPOINT_NR), ref fADDPOINT_NR, value); }
        }
        string fCUSTOMERCOMMENT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string CUSTOMERCOMMENT_TX
        {
            get { return fCUSTOMERCOMMENT_TX; }
            set { SetPropertyValue<string>(nameof(CUSTOMERCOMMENT_TX), ref fCUSTOMERCOMMENT_TX, value); }
        }
        string fCSCOMMENT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string CSCOMMENT_TX
        {
            get { return fCSCOMMENT_TX; }
            set { SetPropertyValue<string>(nameof(CSCOMMENT_TX), ref fCSCOMMENT_TX, value); }
        }
        string fOPERATORCOMMENT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string OPERATORCOMMENT_TX
        {
            get { return fOPERATORCOMMENT_TX; }
            set { SetPropertyValue<string>(nameof(OPERATORCOMMENT_TX), ref fOPERATORCOMMENT_TX, value); }
        }
        long fDETCOUNT_NR;
        public long DETCOUNT_NR
        {
            get { return fDETCOUNT_NR; }
            set { SetPropertyValue<long>(nameof(DETCOUNT_NR), ref fDETCOUNT_NR, value); }
        }
        int fINVOICE_FL;
        public int INVOICE_FL
        {
            get { return fINVOICE_FL; }
            set { SetPropertyValue<int>(nameof(INVOICE_FL), ref fINVOICE_FL, value); }
        }
        string fINVOICECOMMENT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string INVOICECOMMENT_TX
        {
            get { return fINVOICECOMMENT_TX; }
            set { SetPropertyValue<string>(nameof(INVOICECOMMENT_TX), ref fINVOICECOMMENT_TX, value); }
        }
        long fPRTINVOICECOUNT_NR;
        public long PRTINVOICECOUNT_NR
        {
            get { return fPRTINVOICECOUNT_NR; }
            set { SetPropertyValue<long>(nameof(PRTINVOICECOUNT_NR), ref fPRTINVOICECOUNT_NR, value); }
        }
        string fPRTINVOICE_DT;
        [Size(SizeAttribute.Unlimited)]
        public string PRTINVOICE_DT
        {
            get { return fPRTINVOICE_DT; }
            set { SetPropertyValue<string>(nameof(PRTINVOICE_DT), ref fPRTINVOICE_DT, value); }
        }
        string fPRTINVOICEUSER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PRTINVOICEUSER_CD
        {
            get { return fPRTINVOICEUSER_CD; }
            set { SetPropertyValue<string>(nameof(PRTINVOICEUSER_CD), ref fPRTINVOICEUSER_CD, value); }
        }
        string fPRTINVOICEUSER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string PRTINVOICEUSER_TX
        {
            get { return fPRTINVOICEUSER_TX; }
            set { SetPropertyValue<string>(nameof(PRTINVOICEUSER_TX), ref fPRTINVOICEUSER_TX, value); }
        }
        int fDELIBOX_FL;
        public int DELIBOX_FL
        {
            get { return fDELIBOX_FL; }
            set { SetPropertyValue<int>(nameof(DELIBOX_FL), ref fDELIBOX_FL, value); }
        }
        string fDELIITEM_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DELIITEM_TX
        {
            get { return fDELIITEM_TX; }
            set { SetPropertyValue<string>(nameof(DELIITEM_TX), ref fDELIITEM_TX, value); }
        }
        string fDELICOMMENT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DELICOMMENT_TX
        {
            get { return fDELICOMMENT_TX; }
            set { SetPropertyValue<string>(nameof(DELICOMMENT_TX), ref fDELICOMMENT_TX, value); }
        }
        long fPRTDELICOUNT_NR;
        public long PRTDELICOUNT_NR
        {
            get { return fPRTDELICOUNT_NR; }
            set { SetPropertyValue<long>(nameof(PRTDELICOUNT_NR), ref fPRTDELICOUNT_NR, value); }
        }
        string fPRTDELI_DT;
        [Size(SizeAttribute.Unlimited)]
        public string PRTDELI_DT
        {
            get { return fPRTDELI_DT; }
            set { SetPropertyValue<string>(nameof(PRTDELI_DT), ref fPRTDELI_DT, value); }
        }
        string fPRTDELIUSER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PRTDELIUSER_CD
        {
            get { return fPRTDELIUSER_CD; }
            set { SetPropertyValue<string>(nameof(PRTDELIUSER_CD), ref fPRTDELIUSER_CD, value); }
        }
        string fPRTDELIUSER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string PRTDELIUSER_TX
        {
            get { return fPRTDELIUSER_TX; }
            set { SetPropertyValue<string>(nameof(PRTDELIUSER_TX), ref fPRTDELIUSER_TX, value); }
        }
        string fPACKNO1_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO1_CD
        {
            get { return fPACKNO1_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO1_CD), ref fPACKNO1_CD, value); }
        }
        string fPACKNO2_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO2_CD
        {
            get { return fPACKNO2_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO2_CD), ref fPACKNO2_CD, value); }
        }
        string fPACKNO3_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO3_CD
        {
            get { return fPACKNO3_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO3_CD), ref fPACKNO3_CD, value); }
        }
        string fPACKNO4_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO4_CD
        {
            get { return fPACKNO4_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO4_CD), ref fPACKNO4_CD, value); }
        }
        string fPACKNO5_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO5_CD
        {
            get { return fPACKNO5_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO5_CD), ref fPACKNO5_CD, value); }
        }
        string fPACKNO6_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO6_CD
        {
            get { return fPACKNO6_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO6_CD), ref fPACKNO6_CD, value); }
        }
        string fPACKNO7_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO7_CD
        {
            get { return fPACKNO7_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO7_CD), ref fPACKNO7_CD, value); }
        }
        string fPACKNO8_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO8_CD
        {
            get { return fPACKNO8_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO8_CD), ref fPACKNO8_CD, value); }
        }
        string fPACKNO9_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO9_CD
        {
            get { return fPACKNO9_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO9_CD), ref fPACKNO9_CD, value); }
        }
        string fPACKNO10_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PACKNO10_CD
        {
            get { return fPACKNO10_CD; }
            set { SetPropertyValue<string>(nameof(PACKNO10_CD), ref fPACKNO10_CD, value); }
        }
        string fOWNERTRANS_CD;
        [Size(SizeAttribute.Unlimited)]
        public string OWNERTRANS_CD
        {
            get { return fOWNERTRANS_CD; }
            set { SetPropertyValue<string>(nameof(OWNERTRANS_CD), ref fOWNERTRANS_CD, value); }
        }
        int fSHIPD_ID;
        public int SHIPD_ID
        {
            get { return fSHIPD_ID; }
            set { SetPropertyValue<int>(nameof(SHIPD_ID), ref fSHIPD_ID, value); }
        }
        string fSTART_DET_DT;
        [Size(SizeAttribute.Unlimited)]
        public string START_DET_DT
        {
            get { return fSTART_DET_DT; }
            set { SetPropertyValue<string>(nameof(START_DET_DT), ref fSTART_DET_DT, value); }
        }
        string fEND_DET_DT;
        [Size(SizeAttribute.Unlimited)]
        public string END_DET_DT
        {
            get { return fEND_DET_DT; }
            set { SetPropertyValue<string>(nameof(END_DET_DT), ref fEND_DET_DT, value); }
        }
        int fSTSHIP_DET_ID;
        public int STSHIP_DET_ID
        {
            get { return fSTSHIP_DET_ID; }
            set { SetPropertyValue<int>(nameof(STSHIP_DET_ID), ref fSTSHIP_DET_ID, value); }
        }
        string fORDERDETNO_CD;
        [Size(450)]
        public string ORDERDETNO_CD
        {
            get { return fORDERDETNO_CD; }
            set { SetPropertyValue<string>(nameof(ORDERDETNO_CD), ref fORDERDETNO_CD, value); }
        }
        string fSKU_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SKU_CD
        {
            get { return fSKU_CD; }
            set { SetPropertyValue<string>(nameof(SKU_CD), ref fSKU_CD, value); }
        }
        string fLOT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string LOT_TX
        {
            get { return fLOT_TX; }
            set { SetPropertyValue<string>(nameof(LOT_TX), ref fLOT_TX, value); }
        }
        string fKANBAN_CD;
        [Size(SizeAttribute.Unlimited)]
        public string KANBAN_CD
        {
            get { return fKANBAN_CD; }
            set { SetPropertyValue<string>(nameof(KANBAN_CD), ref fKANBAN_CD, value); }
        }
        long fCASEPERPALLET_NR;
        public long CASEPERPALLET_NR
        {
            get { return fCASEPERPALLET_NR; }
            set { SetPropertyValue<long>(nameof(CASEPERPALLET_NR), ref fCASEPERPALLET_NR, value); }
        }
        long fPALLETLAYER_NR;
        public long PALLETLAYER_NR
        {
            get { return fPALLETLAYER_NR; }
            set { SetPropertyValue<long>(nameof(PALLETLAYER_NR), ref fPALLETLAYER_NR, value); }
        }
        long fSTACKINGNUMBER_NR;
        public long STACKINGNUMBER_NR
        {
            get { return fSTACKINGNUMBER_NR; }
            set { SetPropertyValue<long>(nameof(STACKINGNUMBER_NR), ref fSTACKINGNUMBER_NR, value); }
        }
        string fSKU_TX;
        [Size(SizeAttribute.Unlimited)]
        public string SKU_TX
        {
            get { return fSKU_TX; }
            set { SetPropertyValue<string>(nameof(SKU_TX), ref fSKU_TX, value); }
        }
        string fTYPELOCA_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPELOCA_CD
        {
            get { return fTYPELOCA_CD; }
            set { SetPropertyValue<string>(nameof(TYPELOCA_CD), ref fTYPELOCA_CD, value); }
        }
        string fSTOCKTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string STOCKTYPE_CD
        {
            get { return fSTOCKTYPE_CD; }
            set { SetPropertyValue<string>(nameof(STOCKTYPE_CD), ref fSTOCKTYPE_CD, value); }
        }
        long fPALLETCAPACITY_NR;
        public long PALLETCAPACITY_NR
        {
            get { return fPALLETCAPACITY_NR; }
            set { SetPropertyValue<long>(nameof(PALLETCAPACITY_NR), ref fPALLETCAPACITY_NR, value); }
        }
        int fORDERPALLET_NR;
        public int ORDERPALLET_NR
        {
            get { return fORDERPALLET_NR; }
            set { SetPropertyValue<int>(nameof(ORDERPALLET_NR), ref fORDERPALLET_NR, value); }
        }
        int fORDERCASE_NR;
        public int ORDERCASE_NR
        {
            get { return fORDERCASE_NR; }
            set { SetPropertyValue<int>(nameof(ORDERCASE_NR), ref fORDERCASE_NR, value); }
        }
        long fORDERBARA_NR;
        public long ORDERBARA_NR
        {
            get { return fORDERBARA_NR; }
            set { SetPropertyValue<long>(nameof(ORDERBARA_NR), ref fORDERBARA_NR, value); }
        }
        long fORDERPCS_NR;
        public long ORDERPCS_NR
        {
            get { return fORDERPCS_NR; }
            set { SetPropertyValue<long>(nameof(ORDERPCS_NR), ref fORDERPCS_NR, value); }
        }
        long fUNITPRICE_NR;
        public long UNITPRICE_NR
        {
            get { return fUNITPRICE_NR; }
            set { SetPropertyValue<long>(nameof(UNITPRICE_NR), ref fUNITPRICE_NR, value); }
        }
        long fUNITADDPOINT_NR;
        public long UNITADDPOINT_NR
        {
            get { return fUNITADDPOINT_NR; }
            set { SetPropertyValue<long>(nameof(UNITADDPOINT_NR), ref fUNITADDPOINT_NR, value); }
        }
        int fBONUS_FL;
        public int BONUS_FL
        {
            get { return fBONUS_FL; }
            set { SetPropertyValue<int>(nameof(BONUS_FL), ref fBONUS_FL, value); }
        }
        long fUNITSALEDISCOUNT_NR;
        public long UNITSALEDISCOUNT_NR
        {
            get { return fUNITSALEDISCOUNT_NR; }
            set { SetPropertyValue<long>(nameof(UNITSALEDISCOUNT_NR), ref fUNITSALEDISCOUNT_NR, value); }
        }
        string fDETCOMMENT_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DETCOMMENT_TX
        {
            get { return fDETCOMMENT_TX; }
            set { SetPropertyValue<string>(nameof(DETCOMMENT_TX), ref fDETCOMMENT_TX, value); }
        }
        string fTYPESHIPAPPLY_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPESHIPAPPLY_CD
        {
            get { return fTYPESHIPAPPLY_CD; }
            set { SetPropertyValue<string>(nameof(TYPESHIPAPPLY_CD), ref fTYPESHIPAPPLY_CD, value); }
        }
        string fTYPESHIPROUTE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPESHIPROUTE_CD
        {
            get { return fTYPESHIPROUTE_CD; }
            set { SetPropertyValue<string>(nameof(TYPESHIPROUTE_CD), ref fTYPESHIPROUTE_CD, value); }
        }
        string fSKUTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SKUTYPE_CD
        {
            get { return fSKUTYPE_CD; }
            set { SetPropertyValue<string>(nameof(SKUTYPE_CD), ref fSKUTYPE_CD, value); }
        }
        string fSUPPLYTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SUPPLYTYPE_CD
        {
            get { return fSUPPLYTYPE_CD; }
            set { SetPropertyValue<string>(nameof(SUPPLYTYPE_CD), ref fSUPPLYTYPE_CD, value); }
        }
        string fSUPPLIER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SUPPLIER_CD
        {
            get { return fSUPPLIER_CD; }
            set { SetPropertyValue<string>(nameof(SUPPLIER_CD), ref fSUPPLIER_CD, value); }
        }
        string fSETSKUGROUPSEQ_NR;
        [Size(SizeAttribute.Unlimited)]
        public string SETSKUGROUPSEQ_NR
        {
            get { return fSETSKUGROUPSEQ_NR; }
            set { SetPropertyValue<string>(nameof(SETSKUGROUPSEQ_NR), ref fSETSKUGROUPSEQ_NR, value); }
        }
        string fPRINTDETTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PRINTDETTYPE_CD
        {
            get { return fPRINTDETTYPE_CD; }
            set { SetPropertyValue<string>(nameof(PRINTDETTYPE_CD), ref fPRINTDETTYPE_CD, value); }
        }
        string fPRINTPICKLISTTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PRINTPICKLISTTYPE_CD
        {
            get { return fPRINTPICKLISTTYPE_CD; }
            set { SetPropertyValue<string>(nameof(PRINTPICKLISTTYPE_CD), ref fPRINTPICKLISTTYPE_CD, value); }
        }
        string fAPPLY_DT;
        [Size(SizeAttribute.Unlimited)]
        public string APPLY_DT
        {
            get { return fAPPLY_DT; }
            set { SetPropertyValue<string>(nameof(APPLY_DT), ref fAPPLY_DT, value); }
        }
        string fAPPLYUSER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string APPLYUSER_CD
        {
            get { return fAPPLYUSER_CD; }
            set { SetPropertyValue<string>(nameof(APPLYUSER_CD), ref fAPPLYUSER_CD, value); }
        }
        string fAPPLYUSER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string APPLYUSER_TX
        {
            get { return fAPPLYUSER_TX; }
            set { SetPropertyValue<string>(nameof(APPLYUSER_TX), ref fAPPLYUSER_TX, value); }
        }
        string fBATCHNO_CD;
        [Size(SizeAttribute.Unlimited)]
        public string BATCHNO_CD
        {
            get { return fBATCHNO_CD; }
            set { SetPropertyValue<string>(nameof(BATCHNO_CD), ref fBATCHNO_CD, value); }
        }
        string fTYPEAPPLY_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPEAPPLY_CD
        {
            get { return fTYPEAPPLY_CD; }
            set { SetPropertyValue<string>(nameof(TYPEAPPLY_CD), ref fTYPEAPPLY_CD, value); }
        }
        string fTYPEBLOCK_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPEBLOCK_CD
        {
            get { return fTYPEBLOCK_CD; }
            set { SetPropertyValue<string>(nameof(TYPEBLOCK_CD), ref fTYPEBLOCK_CD, value); }
        }
        string fTYPECARRY_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPECARRY_CD
        {
            get { return fTYPECARRY_CD; }
            set { SetPropertyValue<string>(nameof(TYPECARRY_CD), ref fTYPECARRY_CD, value); }
        }
        string fWH_CD;
        [Size(450)]
        public string WH_CD
        {
            get { return fWH_CD; }
            set { SetPropertyValue<string>(nameof(WH_CD), ref fWH_CD, value); }
        }
        int fPASSTYPE_CD;
        public int PASSTYPE_CD
        {
            get { return fPASSTYPE_CD; }
            set { SetPropertyValue<int>(nameof(PASSTYPE_CD), ref fPASSTYPE_CD, value); }
        }
        string fUSELIMIT_DT;
        [Size(SizeAttribute.Unlimited)]
        public string USELIMIT_DT
        {
            get { return fUSELIMIT_DT; }
            set { SetPropertyValue<string>(nameof(USELIMIT_DT), ref fUSELIMIT_DT, value); }
        }
        string fMANAGETYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string MANAGETYPE_CD
        {
            get { return fMANAGETYPE_CD; }
            set { SetPropertyValue<string>(nameof(MANAGETYPE_CD), ref fMANAGETYPE_CD, value); }
        }
        string fSHIPTYPE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SHIPTYPE_CD
        {
            get { return fSHIPTYPE_CD; }
            set { SetPropertyValue<string>(nameof(SHIPTYPE_CD), ref fSHIPTYPE_CD, value); }
        }
        string fMANUFACTURER_CD;
        [Size(SizeAttribute.Unlimited)]
        public string MANUFACTURER_CD
        {
            get { return fMANUFACTURER_CD; }
            set { SetPropertyValue<string>(nameof(MANUFACTURER_CD), ref fMANUFACTURER_CD, value); }
        }
        string fPALLETDETNO_CD;
        [Size(SizeAttribute.Unlimited)]
        public string PALLETDETNO_CD
        {
            get { return fPALLETDETNO_CD; }
            set { SetPropertyValue<string>(nameof(PALLETDETNO_CD), ref fPALLETDETNO_CD, value); }
        }
        int fSTPICK_ID;
        public int STPICK_ID
        {
            get { return fSTPICK_ID; }
            set { SetPropertyValue<int>(nameof(STPICK_ID), ref fSTPICK_ID, value); }
        }
        string fSTPICK_TX;
        [Size(SizeAttribute.Unlimited)]
        public string STPICK_TX
        {
            get { return fSTPICK_TX; }
            set { SetPropertyValue<string>(nameof(STPICK_TX), ref fSTPICK_TX, value); }
        }
        string fTRANSPORTERGROUP_TX;
        [Size(SizeAttribute.Unlimited)]
        public string TRANSPORTERGROUP_TX
        {
            get { return fTRANSPORTERGROUP_TX; }
            set { SetPropertyValue<string>(nameof(TRANSPORTERGROUP_TX), ref fTRANSPORTERGROUP_TX, value); }
        }
        string fTRANSPORTER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string TRANSPORTER_TX
        {
            get { return fTRANSPORTER_TX; }
            set { SetPropertyValue<string>(nameof(TRANSPORTER_TX), ref fTRANSPORTER_TX, value); }
        }
        int fDEFER_FL;
        public int DEFER_FL
        {
            get { return fDEFER_FL; }
            set { SetPropertyValue<int>(nameof(DEFER_FL), ref fDEFER_FL, value); }
        }
        string fDEFER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string DEFER_TX
        {
            get { return fDEFER_TX; }
            set { SetPropertyValue<string>(nameof(DEFER_TX), ref fDEFER_TX, value); }
        }
        string fTYPEPICK_CD;
        [Size(SizeAttribute.Unlimited)]
        public string TYPEPICK_CD
        {
            get { return fTYPEPICK_CD; }
            set { SetPropertyValue<string>(nameof(TYPEPICK_CD), ref fTYPEPICK_CD, value); }
        }
        string fTYPEPICK_TX;
        [Size(SizeAttribute.Unlimited)]
        public string TYPEPICK_TX
        {
            get { return fTYPEPICK_TX; }
            set { SetPropertyValue<string>(nameof(TYPEPICK_TX), ref fTYPEPICK_TX, value); }
        }
        string fCASE_CD;
        [Size(SizeAttribute.Unlimited)]
        public string CASE_CD
        {
            get { return fCASE_CD; }
            set { SetPropertyValue<string>(nameof(CASE_CD), ref fCASE_CD, value); }
        }
        string fEXTERIOR_CD;
        [Size(SizeAttribute.Unlimited)]
        public string EXTERIOR_CD
        {
            get { return fEXTERIOR_CD; }
            set { SetPropertyValue<string>(nameof(EXTERIOR_CD), ref fEXTERIOR_CD, value); }
        }
        string fSIZE_TX;
        [Size(SizeAttribute.Unlimited)]
        public string SIZE_TX
        {
            get { return fSIZE_TX; }
            set { SetPropertyValue<string>(nameof(SIZE_TX), ref fSIZE_TX, value); }
        }
        string fSRCLOCA_CD;
        [Size(SizeAttribute.Unlimited)]
        public string SRCLOCA_CD
        {
            get { return fSRCLOCA_CD; }
            set { SetPropertyValue<string>(nameof(SRCLOCA_CD), ref fSRCLOCA_CD, value); }
        }
        int fPALLET_NR;
        public int PALLET_NR
        {
            get { return fPALLET_NR; }
            set { SetPropertyValue<int>(nameof(PALLET_NR), ref fPALLET_NR, value); }
        }
        long fPALLET_CASE_NR;
        public long PALLET_CASE_NR
        {
            get { return fPALLET_CASE_NR; }
            set { SetPropertyValue<long>(nameof(PALLET_CASE_NR), ref fPALLET_CASE_NR, value); }
        }
        int fCASE_NR;
        public int CASE_NR
        {
            get { return fCASE_NR; }
            set { SetPropertyValue<int>(nameof(CASE_NR), ref fCASE_NR, value); }
        }
        long fPCSPERCASE_NR;
        public long PCSPERCASE_NR
        {
            get { return fPCSPERCASE_NR; }
            set { SetPropertyValue<long>(nameof(PCSPERCASE_NR), ref fPCSPERCASE_NR, value); }
        }
        long fBARA_NR;
        public long BARA_NR
        {
            get { return fBARA_NR; }
            set { SetPropertyValue<long>(nameof(BARA_NR), ref fBARA_NR, value); }
        }
        long fPCS_NR;
        public long PCS_NR
        {
            get { return fPCS_NR; }
            set { SetPropertyValue<long>(nameof(PCS_NR), ref fPCS_NR, value); }
        }
        long fPCSCUBIC_NR;
        public long PCSCUBIC_NR
        {
            get { return fPCSCUBIC_NR; }
            set { SetPropertyValue<long>(nameof(PCSCUBIC_NR), ref fPCSCUBIC_NR, value); }
        }
        double fWEIGHT_NR;
        public double WEIGHT_NR
        {
            get { return fWEIGHT_NR; }
            set { SetPropertyValue<double>(nameof(WEIGHT_NR), ref fWEIGHT_NR, value); }
        }
        string fAPPLYGROUP_CD;
        [Size(SizeAttribute.Unlimited)]
        public string APPLYGROUP_CD
        {
            get { return fAPPLYGROUP_CD; }
            set { SetPropertyValue<string>(nameof(APPLYGROUP_CD), ref fAPPLYGROUP_CD, value); }
        }
        string fSRCSTART_DT;
        [Size(SizeAttribute.Unlimited)]
        public string SRCSTART_DT
        {
            get { return fSRCSTART_DT; }
            set { SetPropertyValue<string>(nameof(SRCSTART_DT), ref fSRCSTART_DT, value); }
        }
        string fSRCEND_DT;
        [Size(SizeAttribute.Unlimited)]
        public string SRCEND_DT
        {
            get { return fSRCEND_DT; }
            set { SetPropertyValue<string>(nameof(SRCEND_DT), ref fSRCEND_DT, value); }
        }
        int fSRCLOCASTOCKC_ID;
        public int SRCLOCASTOCKC_ID
        {
            get { return fSRCLOCASTOCKC_ID; }
            set { SetPropertyValue<int>(nameof(SRCLOCASTOCKC_ID), ref fSRCLOCASTOCKC_ID, value); }
        }
        string fADD_DT;
        [Size(SizeAttribute.Unlimited)]
        public string ADD_DT
        {
            get { return fADD_DT; }
            set { SetPropertyValue<string>(nameof(ADD_DT), ref fADD_DT, value); }
        }
        string fCHECKSTART_DT;
        [Size(SizeAttribute.Unlimited)]
        public string CHECKSTART_DT
        {
            get { return fCHECKSTART_DT; }
            set { SetPropertyValue<string>(nameof(CHECKSTART_DT), ref fCHECKSTART_DT, value); }
        }
        DateTime fCHECKEND_DT;
        [Indexed(Name = @"IX_Idsoko_PicksV1_CHECKEND_DT")]
        public DateTime CHECKEND_DT
        {
            get { return fCHECKEND_DT; }
            set { SetPropertyValue<DateTime>(nameof(CHECKEND_DT), ref fCHECKEND_DT, value); }
        }
        string fCHECKHTUSER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string CHECKHTUSER_TX
        {
            get { return fCHECKHTUSER_TX; }
            set { SetPropertyValue<string>(nameof(CHECKHTUSER_TX), ref fCHECKHTUSER_TX, value); }
        }
        string fLOADINGPREPARATIONEND_DT;
        [Size(SizeAttribute.Unlimited)]
        public string LOADINGPREPARATIONEND_DT
        {
            get { return fLOADINGPREPARATIONEND_DT; }
            set { SetPropertyValue<string>(nameof(LOADINGPREPARATIONEND_DT), ref fLOADINGPREPARATIONEND_DT, value); }
        }
        string fLOADINGPREPARATIONHTUSER_TX;
        [Size(SizeAttribute.Unlimited)]
        public string LOADINGPREPARATIONHTUSER_TX
        {
            get { return fLOADINGPREPARATIONHTUSER_TX; }
            set { SetPropertyValue<string>(nameof(LOADINGPREPARATIONHTUSER_TX), ref fLOADINGPREPARATIONHTUSER_TX, value); }
        }
        DateTime fSHIPEND_TX;
        public DateTime SHIPEND_TX
        {
            get { return fSHIPEND_TX; }
            set { SetPropertyValue<DateTime>(nameof(SHIPEND_TX), ref fSHIPEND_TX, value); }
        }
        string fentity;
        [Size(SizeAttribute.Unlimited)]
        public string entity
        {
            get { return fentity; }
            set { SetPropertyValue<string>(nameof(entity), ref fentity, value); }
        }
        DateTime ftimestamp;
        [Indexed(Name = @"nci_wi_Idsoko_PicksV1_E376D4C30F5BAE8E072EECE77F241ED8")]
        public DateTime timestamp
        {
            get { return ftimestamp; }
            set { SetPropertyValue<DateTime>(nameof(timestamp), ref ftimestamp, value); }
        }
    }

}
