//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class InvitationHistories : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        string fInvitationSentBy;
        [Size(SizeAttribute.Unlimited)]
        public string InvitationSentBy
        {
            get { return fInvitationSentBy; }
            set { SetPropertyValue<string>(nameof(InvitationSentBy), ref fInvitationSentBy, value); }
        }
        DateTime fInvitationSentAt;
        public DateTime InvitationSentAt
        {
            get { return fInvitationSentAt; }
            set { SetPropertyValue<DateTime>(nameof(InvitationSentAt), ref fInvitationSentAt, value); }
        }
        Guid fInvitationSentTo;
        public Guid InvitationSentTo
        {
            get { return fInvitationSentTo; }
            set { SetPropertyValue<Guid>(nameof(InvitationSentTo), ref fInvitationSentTo, value); }
        }
    }

}
