//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class IoTs : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>(nameof(Id), ref fId, value); }
        }
        string fIoTID;
        [Size(SizeAttribute.Unlimited)]
        public string IoTID
        {
            get { return fIoTID; }
            set { SetPropertyValue<string>(nameof(IoTID), ref fIoTID, value); }
        }
        int fManagementSection;
        public int ManagementSection
        {
            get { return fManagementSection; }
            set { SetPropertyValue<int>(nameof(ManagementSection), ref fManagementSection, value); }
        }
        string fSerialNumber;
        [Size(SizeAttribute.Unlimited)]
        public string SerialNumber
        {
            get { return fSerialNumber; }
            set { SetPropertyValue<string>(nameof(SerialNumber), ref fSerialNumber, value); }
        }
        DateTime fInitialRegistrationDate;
        public DateTime InitialRegistrationDate
        {
            get { return fInitialRegistrationDate; }
            set { SetPropertyValue<DateTime>(nameof(InitialRegistrationDate), ref fInitialRegistrationDate, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        string fLastUpdater;
        [Size(SizeAttribute.Unlimited)]
        public string LastUpdater
        {
            get { return fLastUpdater; }
            set { SetPropertyValue<string>(nameof(LastUpdater), ref fLastUpdater, value); }
        }
        DateTime fLastUpdatedDate;
        public DateTime LastUpdatedDate
        {
            get { return fLastUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(LastUpdatedDate), ref fLastUpdatedDate, value); }
        }
        string fIMSI;
        [Size(SizeAttribute.Unlimited)]
        public string IMSI
        {
            get { return fIMSI; }
            set { SetPropertyValue<string>(nameof(IMSI), ref fIMSI, value); }
        }
    }

}
