//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class PitagorasV1 : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>(nameof(id), ref fid, value); }
        }
        string froot_id;
        [Indexed(@"retrieval_date;delivery_date;tmcptncd;ckcptncd;unsksptncd;detail_no", Name = @"IX_PitagorasV1_root_id_retrieval_date_delivery_date_tmcptncd_ckcptncd_unsksptncd_detail_no", Unique = true)]
        [Size(450)]
        public string root_id
        {
            get { return froot_id; }
            set { SetPropertyValue<string>(nameof(root_id), ref froot_id, value); }
        }
        DateTime fretrieval_date;
        public DateTime retrieval_date
        {
            get { return fretrieval_date; }
            set { SetPropertyValue<DateTime>(nameof(retrieval_date), ref fretrieval_date, value); }
        }
        string fdelivery_date;
        [Size(450)]
        public string delivery_date
        {
            get { return fdelivery_date; }
            set { SetPropertyValue<string>(nameof(delivery_date), ref fdelivery_date, value); }
        }
        string ftmcptncd;
        [Size(450)]
        public string tmcptncd
        {
            get { return ftmcptncd; }
            set { SetPropertyValue<string>(nameof(tmcptncd), ref ftmcptncd, value); }
        }
        string ftmcptnnm;
        [Size(SizeAttribute.Unlimited)]
        public string tmcptnnm
        {
            get { return ftmcptnnm; }
            set { SetPropertyValue<string>(nameof(tmcptnnm), ref ftmcptnnm, value); }
        }
        string fckcptncd;
        [Size(450)]
        public string ckcptncd
        {
            get { return fckcptncd; }
            set { SetPropertyValue<string>(nameof(ckcptncd), ref fckcptncd, value); }
        }
        string fckcptnnm;
        [Size(SizeAttribute.Unlimited)]
        public string ckcptnnm
        {
            get { return fckcptnnm; }
            set { SetPropertyValue<string>(nameof(ckcptnnm), ref fckcptnnm, value); }
        }
        string fdetail_no;
        [Size(450)]
        public string detail_no
        {
            get { return fdetail_no; }
            set { SetPropertyValue<string>(nameof(detail_no), ref fdetail_no, value); }
        }
        string funsksptncd;
        [Size(450)]
        public string unsksptncd
        {
            get { return funsksptncd; }
            set { SetPropertyValue<string>(nameof(unsksptncd), ref funsksptncd, value); }
        }
        string funsksptnnm;
        [Size(SizeAttribute.Unlimited)]
        public string unsksptnnm
        {
            get { return funsksptnnm; }
            set { SetPropertyValue<string>(nameof(unsksptnnm), ref funsksptnnm, value); }
        }
        string ftransporter_name;
        [Size(SizeAttribute.Unlimited)]
        public string transporter_name
        {
            get { return ftransporter_name; }
            set { SetPropertyValue<string>(nameof(transporter_name), ref ftransporter_name, value); }
        }
        string fshaban;
        [Size(SizeAttribute.Unlimited)]
        public string shaban
        {
            get { return fshaban; }
            set { SetPropertyValue<string>(nameof(shaban), ref fshaban, value); }
        }
        string fkizai;
        [Size(SizeAttribute.Unlimited)]
        public string kizai
        {
            get { return fkizai; }
            set { SetPropertyValue<string>(nameof(kizai), ref fkizai, value); }
        }
        string fjomuin;
        [Size(SizeAttribute.Unlimited)]
        public string jomuin
        {
            get { return fjomuin; }
            set { SetPropertyValue<string>(nameof(jomuin), ref fjomuin, value); }
        }
        string ftel;
        [Size(SizeAttribute.Unlimited)]
        public string tel
        {
            get { return ftel; }
            set { SetPropertyValue<string>(nameof(tel), ref ftel, value); }
        }
        string fremarks;
        [Size(SizeAttribute.Unlimited)]
        public string remarks
        {
            get { return fremarks; }
            set { SetPropertyValue<string>(nameof(remarks), ref fremarks, value); }
        }
        string fdispatch_user_id;
        [Size(SizeAttribute.Unlimited)]
        public string dispatch_user_id
        {
            get { return fdispatch_user_id; }
            set { SetPropertyValue<string>(nameof(dispatch_user_id), ref fdispatch_user_id, value); }
        }
        string fdispatch_user_name;
        [Size(SizeAttribute.Unlimited)]
        public string dispatch_user_name
        {
            get { return fdispatch_user_name; }
            set { SetPropertyValue<string>(nameof(dispatch_user_name), ref fdispatch_user_name, value); }
        }
        string fdispatch_datetime;
        [Size(SizeAttribute.Unlimited)]
        public string dispatch_datetime
        {
            get { return fdispatch_datetime; }
            set { SetPropertyValue<string>(nameof(dispatch_datetime), ref fdispatch_datetime, value); }
        }
        DateTime fdeparture_datetime;
        public DateTime departure_datetime
        {
            get { return fdeparture_datetime; }
            set { SetPropertyValue<DateTime>(nameof(departure_datetime), ref fdeparture_datetime, value); }
        }
        string fdeparture_upduser;
        [Size(SizeAttribute.Unlimited)]
        public string departure_upduser
        {
            get { return fdeparture_upduser; }
            set { SetPropertyValue<string>(nameof(departure_upduser), ref fdeparture_upduser, value); }
        }
        DateTime farrival_datetime;
        public DateTime arrival_datetime
        {
            get { return farrival_datetime; }
            set { SetPropertyValue<DateTime>(nameof(arrival_datetime), ref farrival_datetime, value); }
        }
        string farrival_upduser;
        [Size(SizeAttribute.Unlimited)]
        public string arrival_upduser
        {
            get { return farrival_upduser; }
            set { SetPropertyValue<string>(nameof(arrival_upduser), ref farrival_upduser, value); }
        }
        string fentity;
        [Size(SizeAttribute.Unlimited)]
        public string entity
        {
            get { return fentity; }
            set { SetPropertyValue<string>(nameof(entity), ref fentity, value); }
        }
        DateTime ftimestamp;
        public DateTime timestamp
        {
            get { return ftimestamp; }
            set { SetPropertyValue<DateTime>(nameof(timestamp), ref ftimestamp, value); }
        }
    }

}
