//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class PitagoraMasters : XPLiteObject
    {
        string fsp_conditions_id;
        [Key]
        [Size(450)]
        public string sp_conditions_id
        {
            get { return fsp_conditions_id; }
            set { SetPropertyValue<string>(nameof(sp_conditions_id), ref fsp_conditions_id, value); }
        }
        string fPTNCD;
        [Size(SizeAttribute.Unlimited)]
        public string PTNCD
        {
            get { return fPTNCD; }
            set { SetPropertyValue<string>(nameof(PTNCD), ref fPTNCD, value); }
        }
        string fNNSICD;
        [Size(SizeAttribute.Unlimited)]
        public string NNSICD
        {
            get { return fNNSICD; }
            set { SetPropertyValue<string>(nameof(NNSICD), ref fNNSICD, value); }
        }
        string fJGSCD;
        [Size(SizeAttribute.Unlimited)]
        public string JGSCD
        {
            get { return fJGSCD; }
            set { SetPropertyValue<string>(nameof(JGSCD), ref fJGSCD, value); }
        }
        string fSNTCD;
        [Size(SizeAttribute.Unlimited)]
        public string SNTCD
        {
            get { return fSNTCD; }
            set { SetPropertyValue<string>(nameof(SNTCD), ref fSNTCD, value); }
        }
        string fUNSKSCD;
        [Size(SizeAttribute.Unlimited)]
        public string UNSKSCD
        {
            get { return fUNSKSCD; }
            set { SetPropertyValue<string>(nameof(UNSKSCD), ref fUNSKSCD, value); }
        }
        string fSYUKAP;
        [Size(SizeAttribute.Unlimited)]
        public string SYUKAP
        {
            get { return fSYUKAP; }
            set { SetPropertyValue<string>(nameof(SYUKAP), ref fSYUKAP, value); }
        }
        string fSEKKBN;
        [Size(SizeAttribute.Unlimited)]
        public string SEKKBN
        {
            get { return fSEKKBN; }
            set { SetPropertyValue<string>(nameof(SEKKBN), ref fSEKKBN, value); }
        }
        string fNHNSKCD;
        [Size(SizeAttribute.Unlimited)]
        public string NHNSKCD
        {
            get { return fNHNSKCD; }
            set { SetPropertyValue<string>(nameof(NHNSKCD), ref fNHNSKCD, value); }
        }
        string fNKTISFRG;
        [Size(SizeAttribute.Unlimited)]
        public string NKTISFRG
        {
            get { return fNKTISFRG; }
            set { SetPropertyValue<string>(nameof(NKTISFRG), ref fNKTISFRG, value); }
        }
        string fSKTISFRG;
        [Size(SizeAttribute.Unlimited)]
        public string SKTISFRG
        {
            get { return fSKTISFRG; }
            set { SetPropertyValue<string>(nameof(SKTISFRG), ref fSKTISFRG, value); }
        }
        string fZKTISFRG;
        [Size(SizeAttribute.Unlimited)]
        public string ZKTISFRG
        {
            get { return fZKTISFRG; }
            set { SetPropertyValue<string>(nameof(ZKTISFRG), ref fZKTISFRG, value); }
        }
        DateTime fadd_datetime;
        public DateTime add_datetime
        {
            get { return fadd_datetime; }
            set { SetPropertyValue<DateTime>(nameof(add_datetime), ref fadd_datetime, value); }
        }
        string fadd_user_id;
        [Size(SizeAttribute.Unlimited)]
        public string add_user_id
        {
            get { return fadd_user_id; }
            set { SetPropertyValue<string>(nameof(add_user_id), ref fadd_user_id, value); }
        }
        string fadd_user_name;
        [Size(SizeAttribute.Unlimited)]
        public string add_user_name
        {
            get { return fadd_user_name; }
            set { SetPropertyValue<string>(nameof(add_user_name), ref fadd_user_name, value); }
        }
        string fadd_user_agent;
        [Size(SizeAttribute.Unlimited)]
        public string add_user_agent
        {
            get { return fadd_user_agent; }
            set { SetPropertyValue<string>(nameof(add_user_agent), ref fadd_user_agent, value); }
        }
        string fadd_ip;
        [Size(SizeAttribute.Unlimited)]
        public string add_ip
        {
            get { return fadd_ip; }
            set { SetPropertyValue<string>(nameof(add_ip), ref fadd_ip, value); }
        }
        string fentity;
        [Size(SizeAttribute.Unlimited)]
        public string entity
        {
            get { return fentity; }
            set { SetPropertyValue<string>(nameof(entity), ref fentity, value); }
        }
        DateTime ftimestamp;
        [ColumnDbDefaultValue("('0001-01-01T00:00:00.0000000')")]
        public DateTime timestamp
        {
            get { return ftimestamp; }
            set { SetPropertyValue<DateTime>(nameof(timestamp), ref ftimestamp, value); }
        }
    }

}
