//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class RegisteredUsers : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        string fCompanyName;
        [Size(SizeAttribute.Unlimited)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>(nameof(CompanyName), ref fCompanyName, value); }
        }
        string fBranch;
        [Size(SizeAttribute.Unlimited)]
        public string Branch
        {
            get { return fBranch; }
            set { SetPropertyValue<string>(nameof(Branch), ref fBranch, value); }
        }
        string fSurname;
        [Size(SizeAttribute.Unlimited)]
        public string Surname
        {
            get { return fSurname; }
            set { SetPropertyValue<string>(nameof(Surname), ref fSurname, value); }
        }
        string fFirstName;
        [Size(SizeAttribute.Unlimited)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fSurnameKana;
        [Size(SizeAttribute.Unlimited)]
        public string SurnameKana
        {
            get { return fSurnameKana; }
            set { SetPropertyValue<string>(nameof(SurnameKana), ref fSurnameKana, value); }
        }
        string fFirstNameKana;
        [Size(SizeAttribute.Unlimited)]
        public string FirstNameKana
        {
            get { return fFirstNameKana; }
            set { SetPropertyValue<string>(nameof(FirstNameKana), ref fFirstNameKana, value); }
        }
        string fMailAddress;
        [Size(SizeAttribute.Unlimited)]
        public string MailAddress
        {
            get { return fMailAddress; }
            set { SetPropertyValue<string>(nameof(MailAddress), ref fMailAddress, value); }
        }
        string fPhoneNumber;
        [Size(SizeAttribute.Unlimited)]
        public string PhoneNumber
        {
            get { return fPhoneNumber; }
            set { SetPropertyValue<string>(nameof(PhoneNumber), ref fPhoneNumber, value); }
        }
        string fClientIPAddress;
        [Size(SizeAttribute.Unlimited)]
        public string ClientIPAddress
        {
            get { return fClientIPAddress; }
            set { SetPropertyValue<string>(nameof(ClientIPAddress), ref fClientIPAddress, value); }
        }
        string fClientBrowser;
        [Size(SizeAttribute.Unlimited)]
        public string ClientBrowser
        {
            get { return fClientBrowser; }
            set { SetPropertyValue<string>(nameof(ClientBrowser), ref fClientBrowser, value); }
        }
        string fLocation;
        [Size(SizeAttribute.Unlimited)]
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fStatus;
        [Size(SizeAttribute.Unlimited)]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fRegistrationNumber;
        [Size(SizeAttribute.Unlimited)]
        public string RegistrationNumber
        {
            get { return fRegistrationNumber; }
            set { SetPropertyValue<string>(nameof(RegistrationNumber), ref fRegistrationNumber, value); }
        }
        DateTime fTermsOfUse1AcceptedDateTime;
        [ColumnDbDefaultValue("('0001-01-01T00:00:00.0000000')")]
        public DateTime TermsOfUse1AcceptedDateTime
        {
            get { return fTermsOfUse1AcceptedDateTime; }
            set { SetPropertyValue<DateTime>(nameof(TermsOfUse1AcceptedDateTime), ref fTermsOfUse1AcceptedDateTime, value); }
        }
        string fTermsOfUse1Version;
        [Size(SizeAttribute.Unlimited)]
        public string TermsOfUse1Version
        {
            get { return fTermsOfUse1Version; }
            set { SetPropertyValue<string>(nameof(TermsOfUse1Version), ref fTermsOfUse1Version, value); }
        }
        DateTime fTermsOfUse2AcceptedDateTime;
        [ColumnDbDefaultValue("('0001-01-01T00:00:00.0000000')")]
        public DateTime TermsOfUse2AcceptedDateTime
        {
            get { return fTermsOfUse2AcceptedDateTime; }
            set { SetPropertyValue<DateTime>(nameof(TermsOfUse2AcceptedDateTime), ref fTermsOfUse2AcceptedDateTime, value); }
        }
        string fTermsOfUse2Version;
        [Size(SizeAttribute.Unlimited)]
        public string TermsOfUse2Version
        {
            get { return fTermsOfUse2Version; }
            set { SetPropertyValue<string>(nameof(TermsOfUse2Version), ref fTermsOfUse2Version, value); }
        }
        string fAddress;
        [Size(SizeAttribute.Unlimited)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCode;
        [Size(10)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fPassword;
        [Size(SizeAttribute.Unlimited)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
    }

}
