//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class ReleaseNotes : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fText;
        [Size(SizeAttribute.Unlimited)]
        public string Text
        {
            get { return fText; }
            set { SetPropertyValue<string>(nameof(Text), ref fText, value); }
        }
        string fUpdatedBy;
        [Size(SizeAttribute.Unlimited)]
        public string UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<string>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
        DateTime fUpdatedAt;
        public DateTime UpdatedAt
        {
            get { return fUpdatedAt; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedAt), ref fUpdatedAt, value); }
        }
    }

}
