//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class SalesOffices : XPLiteObject
    {
        string fSalesOfficeCode;
        [Key]
        [Size(450)]
        public string SalesOfficeCode
        {
            get { return fSalesOfficeCode; }
            set { SetPropertyValue<string>(nameof(SalesOfficeCode), ref fSalesOfficeCode, value); }
        }
        string fSalesOfficeFullName;
        [Size(SizeAttribute.Unlimited)]
        public string SalesOfficeFullName
        {
            get { return fSalesOfficeFullName; }
            set { SetPropertyValue<string>(nameof(SalesOfficeFullName), ref fSalesOfficeFullName, value); }
        }
        string fSalesOfficeShortName;
        [Size(SizeAttribute.Unlimited)]
        public string SalesOfficeShortName
        {
            get { return fSalesOfficeShortName; }
            set { SetPropertyValue<string>(nameof(SalesOfficeShortName), ref fSalesOfficeShortName, value); }
        }
    }

}
