//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class SecurityRoles : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fRoleName;
        [Size(50)]
        public string RoleName
        {
            get { return fRoleName; }
            set { SetPropertyValue<string>(nameof(RoleName), ref fRoleName, value); }
        }
        [Association(@"ApplicationUsersReferencesSecurityRoles")]
        public XPCollection<ApplicationUsers> ApplicationUsersCollection { get { return GetCollection<ApplicationUsers>(nameof(ApplicationUsersCollection)); } }
        [Association(@"InvitedUsersReferencesSecurityRoles")]
        public XPCollection<InvitedUsers> InvitedUsersCollection { get { return GetCollection<InvitedUsers>(nameof(InvitedUsersCollection)); } }
    }

}
