//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class Shippers2 : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fShipperTradingName;
        [Indexed(Name = @"IX_Shippers2_ShipperTradingName", Unique = true)]
        [Size(450)]
        public string ShipperTradingName
        {
            get { return fShipperTradingName; }
            set { SetPropertyValue<string>(nameof(ShipperTradingName), ref fShipperTradingName, value); }
        }
    }

}
