//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class SokoChangeFeeds : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>(nameof(Id), ref fId, value); }
        }
        string fBody;
        [Size(SizeAttribute.Unlimited)]
        public string Body
        {
            get { return fBody; }
            set { SetPropertyValue<string>(nameof(Body), ref fBody, value); }
        }
        DateTime fCreatedDateTime;
        public DateTime CreatedDateTime
        {
            get { return fCreatedDateTime; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDateTime), ref fCreatedDateTime, value); }
        }
        DateTime fPropcessedDateTime;
        public DateTime PropcessedDateTime
        {
            get { return fPropcessedDateTime; }
            set { SetPropertyValue<DateTime>(nameof(PropcessedDateTime), ref fPropcessedDateTime, value); }
        }
    }

}
