//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class Transporters : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fShipperCode;
        [Indexed(@"SalesOfficeCode;TransporterCode", Name = @"IX_Transporters_ShipperCode_SalesOfficeCode_TransporterCode", Unique = true)]
        [Size(10)]
        public string ShipperCode
        {
            get { return fShipperCode; }
            set { SetPropertyValue<string>(nameof(ShipperCode), ref fShipperCode, value); }
        }
        string fSalesOfficeCode;
        [Size(10)]
        public string SalesOfficeCode
        {
            get { return fSalesOfficeCode; }
            set { SetPropertyValue<string>(nameof(SalesOfficeCode), ref fSalesOfficeCode, value); }
        }
        string fTransporterCode;
        [Size(450)]
        public string TransporterCode
        {
            get { return fTransporterCode; }
            set { SetPropertyValue<string>(nameof(TransporterCode), ref fTransporterCode, value); }
        }
        string fTransporterName;
        [Size(SizeAttribute.Unlimited)]
        public string TransporterName
        {
            get { return fTransporterName; }
            set { SetPropertyValue<string>(nameof(TransporterName), ref fTransporterName, value); }
        }
        DateTime fLastUpdatedAt;
        [ColumnDbDefaultValue("('0001-01-01T00:00:00.0000000')")]
        public DateTime LastUpdatedAt
        {
            get { return fLastUpdatedAt; }
            set { SetPropertyValue<DateTime>(nameof(LastUpdatedAt), ref fLastUpdatedAt, value); }
        }
    }

}
