//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class UserManuals : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>(nameof(Id), ref fId, value); }
        }
        string fFunction;
        [Size(SizeAttribute.Unlimited)]
        public string Function
        {
            get { return fFunction; }
            set { SetPropertyValue<string>(nameof(Function), ref fFunction, value); }
        }
        string fAction;
        [Size(SizeAttribute.Unlimited)]
        public string Action
        {
            get { return fAction; }
            set { SetPropertyValue<string>(nameof(Action), ref fAction, value); }
        }
        string fAudience;
        [Size(SizeAttribute.Unlimited)]
        public string Audience
        {
            get { return fAudience; }
            set { SetPropertyValue<string>(nameof(Audience), ref fAudience, value); }
        }
        byte[] fUserManualBytes;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] UserManualBytes
        {
            get { return fUserManualBytes; }
            set { SetPropertyValue<byte[]>(nameof(UserManualBytes), ref fUserManualBytes, value); }
        }
        string fFileName;
        [Size(SizeAttribute.Unlimited)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>(nameof(FileName), ref fFileName, value); }
        }
        string fLastUpdatedBy;
        [Size(SizeAttribute.Unlimited)]
        public string LastUpdatedBy
        {
            get { return fLastUpdatedBy; }
            set { SetPropertyValue<string>(nameof(LastUpdatedBy), ref fLastUpdatedBy, value); }
        }
        DateTime fLastUpdatedOn;
        public DateTime LastUpdatedOn
        {
            get { return fLastUpdatedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastUpdatedOn), ref fLastUpdatedOn, value); }
        }
    }

}
