//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class UserViews : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        string fUserId;
        [Indexed(@"ViewName;ComponentName", Name = @"IX_UserViews_UserId_ViewName_ComponentName", Unique = true)]
        [Size(450)]
        public string UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<string>(nameof(UserId), ref fUserId, value); }
        }
        string fViewName;
        [Size(450)]
        public string ViewName
        {
            get { return fViewName; }
            set { SetPropertyValue<string>(nameof(ViewName), ref fViewName, value); }
        }
        string fComponentName;
        [Size(450)]
        public string ComponentName
        {
            get { return fComponentName; }
            set { SetPropertyValue<string>(nameof(ComponentName), ref fComponentName, value); }
        }
        string fLayoutString;
        [Size(SizeAttribute.Unlimited)]
        public string LayoutString
        {
            get { return fLayoutString; }
            set { SetPropertyValue<string>(nameof(LayoutString), ref fLayoutString, value); }
        }
    }

}
