//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class UserAudit : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fUpdatedBy;
        [Size(SizeAttribute.Unlimited)]
        public string UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<string>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
        DateTime fModifiedAt;
        public DateTime ModifiedAt
        {
            get { return fModifiedAt; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedAt), ref fModifiedAt, value); }
        }
        string fField;
        [Size(SizeAttribute.Unlimited)]
        public string Field
        {
            get { return fField; }
            set { SetPropertyValue<string>(nameof(Field), ref fField, value); }
        }
        string fOldValue;
        [Size(SizeAttribute.Unlimited)]
        public string OldValue
        {
            get { return fOldValue; }
            set { SetPropertyValue<string>(nameof(OldValue), ref fOldValue, value); }
        }
        string fNewValue;
        [Size(SizeAttribute.Unlimited)]
        public string NewValue
        {
            get { return fNewValue; }
            set { SetPropertyValue<string>(nameof(NewValue), ref fNewValue, value); }
        }
        string fTargetUserId;
        [Size(SizeAttribute.Unlimited)]
        public string TargetUserId
        {
            get { return fTargetUserId; }
            set { SetPropertyValue<string>(nameof(TargetUserId), ref fTargetUserId, value); }
        }
    }

}
