//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tracking.web.sql_trackingdb_stag
{

    public partial class Warehouses : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fShipperCode;
        [Indexed(@"SalesOfficeCode;warehouse_code", Name = @"IX_Warehouses_ShipperCode_SalesOfficeCode_warehouse_code", Unique = true)]
        [Size(10)]
        public string ShipperCode
        {
            get { return fShipperCode; }
            set { SetPropertyValue<string>(nameof(ShipperCode), ref fShipperCode, value); }
        }
        string fSalesOfficeCode;
        [Size(10)]
        public string SalesOfficeCode
        {
            get { return fSalesOfficeCode; }
            set { SetPropertyValue<string>(nameof(SalesOfficeCode), ref fSalesOfficeCode, value); }
        }
        string fwarehouse_code;
        [Size(450)]
        public string warehouse_code
        {
            get { return fwarehouse_code; }
            set { SetPropertyValue<string>(nameof(warehouse_code), ref fwarehouse_code, value); }
        }
        string fwarehouse_name;
        [Size(SizeAttribute.Unlimited)]
        public string warehouse_name
        {
            get { return fwarehouse_name; }
            set { SetPropertyValue<string>(nameof(warehouse_name), ref fwarehouse_name, value); }
        }
        DateTime fLastUpdatedAt;
        [ColumnDbDefaultValue("('0001-01-01T00:00:00.0000000')")]
        public DateTime LastUpdatedAt
        {
            get { return fLastUpdatedAt; }
            set { SetPropertyValue<DateTime>(nameof(LastUpdatedAt), ref fLastUpdatedAt, value); }
        }
    }

}
